projects:
  default:
    schema:
      ${VITE_STORYBLOK_GRAPHQL_ENDPOINT}:
        method: POST
        headers:
          token: ${STORYBLOK_API_TOKEN}
          version: ${STORYBLOK_API_VERSION}
    documents: '**/*.gql'
    extensions:
      endpoints:
        default:
          url:
            ${VITE_STORYBLOK_GRAPHQL_ENDPOINT}:
              method: POST
              headers:
                token: ${STORYBLOK_API_TOKEN}
                version: ${STORYBLOK_API_VERSION}
      codegen:
        generates:
          ./src/lib/graphql/_gen/graphqlTypes.ts:
            plugins:
              - typescript
              - typescript-operations
              - typed-document-node
              - typescript-document-nodes

          ./src/lib/graphql/_gen/graphqlStores.ts:
            plugins:
              - '@kitql/graphql-codegen'
            config:
              importBaseTypesFrom: $lib/graphql/_gen/graphqlTypes

        config:
          useTypeImports: true
